language: node_js
node_js:
  - 10

# Need super user permissions to execute this build
sudo: required

services:
  # Have a copy of Docker CLI installed
  - docker

before_install:
  - docker build -t chima25/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chima25/docker-react npm run test -- --coverage
